# Generated by Django 2.1.1 on 2019-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paid_article',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paid_subscription',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='static/image', verbose_name='Тематическое изображение статьи'),
        ),
    ]
