# Generated by Django 2.1.1 on 2019-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190915_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paid_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='paid_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
