# Generated by Django 2.1.1 on 2019-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190915_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='paid_article',
            field=models.BooleanField(default=False, verbose_name='Платная статья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paid_subscription',
            field=models.BooleanField(default=False, verbose_name='Оформлена платная подписка'),
        ),
    ]
